<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'ProjectTest' and '$(Configuration)' == 'Debug'">
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and ('$(Platform)' == '' or '$(Platform)' == 'AnyCPU' or '$(Platform)' == 'x64')">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and '$(Platform)' == 'x86'">win-x86</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and '$(Platform)' == 'ARM64'">win-arm64</RuntimeIdentifier>
    <RuntimeIdentifiers></RuntimeIdentifiers>
  </PropertyGroup>
</Project>
